### ISSUE TITLE
More robust test data cleanup

### ISSUE THREAD

**Issue by jakirkham** [nanshe-org/nanshe#389]
Annoyingly NFS on the cluster is getting slower at cleaning up test data. This is giving us false positives in our tests. Snippet of such a failure shown below. This happened on Python 2.7 and 3.5 so is not dependent on Python version (unsurprisingly). Normally `shutil.rmtree` would always clean out the contents of a directory and then the directories themselves. However, they seems to be some kind of lag between things finally getting removed and a call to `os.rmdir`. We might need to sleep and retry or something else equally annoying and potentially fragile. Sadly it is just the name of the game with this stuff.

```
======================================================================
ERROR: tests.test_nanshe.test_io.test_hdf5.test_serializers.TestSerializers.test_read_numpy_structured_array_from_HDF5_1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/groups/dudman/home/kirkhamj/miniconda/envs/nanshenv3/lib/python3.5/site-packages/nose/case.py", line 385, in tearDown
    try_run(self.inst, ('teardown', 'tearDown'))
  File "/groups/dudman/home/kirkhamj/miniconda/envs/nanshenv3/lib/python3.5/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/groups/dudman/home/kirkhamj/nanshe/tests/test_nanshe/test_io/test_hdf5/test_serializers.py", line 209, in teardown
    shutil.rmtree(self.temp_dir)
  File "/groups/dudman/home/kirkhamj/miniconda/envs/nanshenv3/lib/python3.5/shutil.py", line 478, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/groups/dudman/home/kirkhamj/miniconda/envs/nanshenv3/lib/python3.5/shutil.py", line 476, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/groups/dudman/home/kirkhamj/tmp/tmpqaa9du0d'
```

**Comment by jakirkham** [comment]
Probably the same as issue ( https://github.com/nanshe-org/nanshe/issues/460 ).
